site_name: Tài liệu WeMap
theme:
  name: 'material'
nav:
  - Tổng quan: 'index.md'
  - Người dùng: 
      - Tài khoản: 'account/account.md'
      - API Key: 'account/key.md'
      - Thống kê: 'account/analytics.md'
  - Hiển thị Bản đồ: 
    - Raster tiles: 'maps/raster-tiles.md'
    - Vector tiles: 'maps/vector-tiles.md'
  - Địa điểm:
    # - API địa điểm: 'geocode/place.md'
    - API Search: 'geocode/search.md'
    - API Reverse: 'geocode/reverse.md'
    - API Autocomplete: 'geocode/autocomplete.md'
    - API Địa danh hành chỉnh: 'geocode/pip.md'
  - Chỉ đường:
    - API dẫn đường: 'routing/routing.md'
    - API dẫn đường cho bus: 'routing/bus.md'
  - Android SDK:
    - Cài đặt: 'android-sdk/installing.md'
    - Ví dụ Hiển thị bản đồ: 'android-sdk/map.md'
    - Ví dụ Thêm các lớp bản đồ: 'android-sdk/map-layer.md'
    - Ví dụ Thêm GeoJSON: 'android-sdk/geojson-layer.md'
    - Ví dụ Tìm kiếm: 'android-sdk/search.md'
    - Ví dụ Chỉ đường: 'android-sdk/direction.md'
