site_name: Tài liệu WeMap Web SDK
nav:
  - Trang chủ: index.md
  - WeMap Web SDK:
    - WeMap SDK: Web/readme.md
    - WeMap Web: Web/wemap.md
    - WeGeocoder: Web/wegeocoder.md
    - WeDirections: Web/wedirections.md
    - WeFilterControl: Web/wefilter.md
    - GeoJSON: Web/GeoJSON.md
    - Marker: Web/marker.md
theme:
  name: material
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - javascript
    - css
    - html
copyright: '2020 © WeMap'
